name: ES Lint

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
      - name: Install dependencies
      - name: Lint React
        run: |
          cd PantryNodeReact
          npm install
          npm rum lint
      - name: Lint Node
        run: |
          npm install
          npm rum lint-express
